# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd0c8138563f1ea2eee8cd3a676d1301c88e1d60e9716e1749087deeb4917932237489dd4a81033b42226efddba0da8def002e127c759e13adc852fe0f174cf5

test:
  secret_key_base: 1076620eefe495628a8d11b862024fc969743c3585d18fdc7a606398d13b26f75286fceac0c00d688fd495fe6f63bf536ed75c60721dfdfb1c3b793e9877c054

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
